export const loader = '[data-cy="loader"]';
export const color_default = "rgb(0, 50, 255)";
export const color_modified = "rgb(127, 224, 81)";
export const color_changing = "rgb(210, 82, 225)";
export const element = '[data-cy="border"]';
export const head = '[data-cy="head"]';
export const tail = '[data-cy="tail"]';
export const letter = '[data-cy="letter"]'; 
export const circle = '[data-cy="circle"]'; 
export const index_element = '[data-cy="index"]'; 